version: '2.17'

services:
  database:
    image: mysql:8.0
    container_name: bp-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=bpdb
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
     - bp-mysql:/var/lib/mysql

volumes:
  bp-mysql:
    driver: local

networks:
  bp-mysql:
    driver: bridge